import React from 'react'

function Blogs() {
  return (
    <div>
      <div className="bg-blue-100 p-5 border-2 rounded-lg hover:shadow-2xl hover:scale-105 hover:ease-in-out duration-700"><div className="border-gray-400 min-h-56 dark:bg-black  "><h1 className="text-5xl font-sans">Curated Career Opportunities for you </h1><div className="grid my-10 grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-2"><a className="flex flex-col relative overflow-hidden height-auto text-foreground box-border bg-content1 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 shadow-small rounded-large transition-transform-background motion-reduce:transition-none border-none my-5 mx-auto max-w-3xl dark:bg-gray-200" tabIndex={-1} href="blogs/64c61dff91b7b7168a78cb11"><div className="relative flex w-full p-5 flex-auto flex-col place-content-inherit align-items-inherit h-auto break-words text-left overflow-y-auto subpixel-antialiased"><div className="grid grid-cols-2 lg:grid-cols-6 gap-1 items-center "><div className="col-span-4"><div className="flex gap-2"><span tabIndex={-1} className="flex relative justify-center items-center box-border overflow-hidden align-middle z-10 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 w-10 h-10 text-tiny bg-default text-default-foreground rounded-full"><img src="https://qbytespace-backend.onrender.com/static/avatar/qbytespace-avatar-1690704311076-wp8387365.jpg" className="flex object-cover w-full h-full transition-opacity !duration-500 opacity-0 data-[loaded=true]:opacity-100" alt="avatar" data-loaded="true" /></span><div className="flex flex-col items-start justify-center"><span className="text-small font-semibold leading-none text-default-600">Suraj Jadhav</span><span className="text-small tracking-tight text-default-400">user</span></div></div><div className="pt-2"><h1 className="text-xl font-bold leading-6">IBM Summer Internship 2023: Gain Real-World Experience and Launch Your Career</h1><img src="https://img-c.udemycdn.com/course/240x135/4789870_53df_2.jpg" className="object-cover mx-auto my-2 w-3/4  rounded-md lg:hidden" /><p className="text-[17px] leading-6 line-clamp-3 mt-1">Are you a student looking for an exciting opportunity to gain real-world experience and kickstart your career? Look no further! IBM has launched the IBM Summer Internship 2023, a prestigious program that offers students the chance to work with the biggest company in the industry. In this blog post, we will explore the details of the internship, including the company's background, benefits, requirements, and how to apply.
      </p></div></div><div className="col-span-3 mx-auto lg:mt-0 mt-4 lg:col-span-2"><div className="relative shadow-black/5 shadow-none rounded-large" style={{ maxWidth: 'fit-content' }}> <img src="https://img-c.udemycdn.com/course/240x135/4789870_53df_2.jpg" className="relative z-10 opacity-0 shadow-black/5 data-[loaded=true]:opacity-100 shadow-none transition-transform-opacity motion-reduce:transition-none !duration-300 rounded-large object-cover mx-auto hidden lg:block xl:block" data-loaded="true" /></div></div></div></div></a><a className="flex flex-col relative overflow-hidden height-auto text-foreground box-border bg-content1 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 shadow-small rounded-large transition-transform-background motion-reduce:transition-none border-none my-5 mx-auto max-w-3xl dark:bg-gray-200" tabIndex={-1} href="blogs/64d7305870684f3102407e07"><div className="relative flex w-full p-5 flex-auto flex-col place-content-inherit align-items-inherit h-auto break-words text-left overflow-y-auto subpixel-antialiased"><div className="grid grid-cols-2 lg:grid-cols-6 gap-1 items-center "><div className="col-span-4"><div className="flex gap-2"><span tabIndex={-1} className="flex relative justify-center items-center box-border overflow-hidden align-middle z-10 outline-none data-[focus-visible=true]:z-10 data-[focus-visible=true]:outline-2 data-[focus-visible=true]:outline-focus data-[focus-visible=true]:outline-offset-2 w-10 h-10 text-tiny bg-default text-default-foreground rounded-full"><img src="https://qbytespace-backend.onrender.com/static/avatar/qbytespace-avatar-1690704311076-wp8387365.jpg" className="flex object-cover w-full h-full transition-opacity !duration-500 opacity-0 data-[loaded=true]:opacity-100" alt="avatar" data-loaded="true" /></span><div className="flex flex-col items-start justify-center"><span className="text-small font-semibold leading-none text-default-600">Suraj Jadhav</span><span className="text-small tracking-tight text-default-400">user</span></div></div><div className="pt-2"><h1 className="text-xl font-bold leading-6">PwC Launched Summer Internship Trainee For 2023 In Bangalore</h1><img src="https://img-c.udemycdn.com/course/240x135/4789870_53df_2.jpg" className="object-cover mx-auto my-2 w-3/4  rounded-md lg:hidden" /><p className="text-[17px] leading-6 line-clamp-3 mt-1">Look no further! PwC India has launched its Summer Internship Trainee program for 2023 in Bangalore. This program offers freshers and students the chance to work with one of the biggest companies in the world and learn from industry experts.
      </p></div></div><div className="col-span-3 mx-auto lg:mt-0 mt-4 lg:col-span-2"><div className="relative shadow-black/5 shadow-none rounded-large" style={{ maxWidth: 'fit-content' }}> <img src="https://img-c.udemycdn.com/course/240x135/4789870_53df_2.jpg" className="relative z-10 opacity-0 shadow-black/5 data-[loaded=true]:opacity-100 shadow-none transition-transform-opacity motion-reduce:transition-none !duration-300 rounded-large object-cover mx-auto hidden lg:block xl:block" data-loaded="true" /></div></div></div></div></a></div></div></div>
    </div>
  )
}

export default Blogs
